language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
sudo: "required"
before_install: "sudo apt-get update && sudo apt-get install -y libcairo2-dev libjpeg8-dev libgif-dev"
script: "npm run-script travis"
